language: java
jdk:
  - openjdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
  
addons:
  sonarcloud:
    organization: "springdoc"
    token:
      secure: $SONAR_TOKEN

after_success:
  - mvn clean deploy -B
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  
  
