language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "springdoc"

script:
  - mvn clean package --settings settings.xml
  - mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN -DskipTests

deploy:
  provider: script
  script: mvn clean deploy -DskipTests --settings settings.xml
  on:
    branch: master
  
