language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "springdoc"
    
script:
  - mvn deploy -DskipTests --settings settings.xml
  - mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN -DskipTests

  
