/*
 *
 *  *
 *  *  *
 *  *  *  *
 *  *  *  *  *
 *  *  *  *  *  * Copyright 2019-2026 the original author or authors.
 *  *  *  *  *  *
 *  *  *  *  *  * Licensed under the Apache License, Version 2.0 (the "License");
 *  *  *  *  *  * you may not use this file except in compliance with the License.
 *  *  *  *  *  * You may obtain a copy of the License at
 *  *  *  *  *  *
 *  *  *  *  *  *      https://www.apache.org/licenses/LICENSE-2.0
 *  *  *  *  *  *
 *  *  *  *  *  * Unless required by applicable law or agreed to in writing, software
 *  *  *  *  *  * distributed under the License is distributed on an "AS IS" BASIS,
 *  *  *  *  *  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  *  *  *  *  * See the License for the specific language governing permissions and
 *  *  *  *  *  * limitations under the License.
 *  *  *  *  *
 *  *  *  *
 *  *  *
 *  *
 *
 */

package test.org.springdoc.api.v31.app25.model;

public enum Specialty {

	ALLERGY_AND_IMMUNOLOGY,
	ADOLESCENT_MEDICINE,
	ANESTHESIOLOGY,
	AEROSPACE_MEDICINE,
	BARIATRICS,
	CARDIOLOGY,
	CARDIOTHORACIC_SURGERY,
	CHILD_AND_ADOLESCENT_PSYCHIATRY,
	CLINICAL_NEUROPHYSIOLOGY,
	COLORECTAL_SURGERY,
	DERMATOLOGY,
	DEVELOPMENTAL_PEDIATRICS,
	EMERGENCY_MEDICINE,
	ENDOCRINOLOGY,
	FAMILY_MEDICINE,
	FORENSIC_PATHOLOGY,
	FORENSIC_PSYCHIATRY,
	GASTROENTEROLOGY,
	GENERAL_SURGERY,
	GENERAL_SURGICAL_ONCOLOGY,
	GERIATRICS,
	GERIATRIC_PSYCHIATRY,
	GYNECOLOGIC_ONCOLOGY,
	HEMATOLOGY,
	HEMATOLOGIC_PATHOLOGY,
	INFECTIOUS_DISEASE,
	INTERNAL_MEDICINE,
	INTERVENTIONAL_RADIOLOGY,
	INTENSIVE_CARE_MEDICINE,
	MATERNAL_FETAL_MEDICINE,
	MEDICAL_BIOCHEMISTRY,
	MEDICAL_GENETICS,
	MEDICAL_ONCOLOGY,
	NEONATOLOGY,
	NEPHROLOGY,
	NEUROLOGY,
	NEUROPATHOLOGY,
	NEUROSURGERY,
	NUCLEAR_MEDICINE,
	OBSTETRICS_AND_GYNECOLOGY,
	OCCUPATIONAL_MEDICINE,
	OPHTHALMOLOGY,
	ORTHOPEDIC_SURGERY,
	ORAL_AND_MAXILLOFACIAL_SURGERY,
	OTORHINOLARYNGOLOGY,
	PALLIATIVE_CARE,
	PATHOLOGY,
	PEDIATRICS,
	PEDIATRIC_ALLERGY_AND_IMMUNOLOGY,
	PEDIATRIC_CARDIOLOGY,
	PEDIATRIC_EMERGENCY_MEDICINE,
	PEDIATRIC_ENDOCRINOLOGY,
	PEDIATRIC_GASTROENTEROLOGY,
	PEDIATRIC_HEMATOLOGY_AND_ONCOLOGY,
	PEDIATRIC_INFECTIOUS_DISEASE,
	PEDIATRIC_NEPHROLOGY,
	PEDIATRIC_RESPIRATORY_MEDICINE,
	PEDIATRIC_RHEUMATOLOGY,
	PEDIATRIC_SURGERY,
	PHYSICAL_MEDICINE_AND_REHABILITATION,
	PLASTIC_RECONSTRUCTIVE_AND_AESTHETIC_SURGERY,
	PSYCHIATRY,
	PUBLIC_HEALTH,
	RADIATION_ONCOLOGY,
	RADIOLOGY,
	REPRODUCTIVE_ENDOCRINOLOGY_AND_INFERTILITY,
	RESPIRATORY_MEDICINE,
	RHEUMATOLOGY,
	SPORTS_MEDICINE,
	THORACIC_SURGERY,
	NEURORADIOLOGY,
	UROLOGY,
	VASCULAR_SURGERY;

}
